### ISSUE TITLE
push didn't trigger circle build of wc_lang

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/karr_lab_build_utils#23]
wc_lang is a downstream dependency (see ), but a circle [build](https://circleci.com/gh/KarrLab/obj_model/398) of obj_model didn't trigger a circle build of wc_lang. is this right?

**Comment by jonrkarr** [comment]
Added more information to CLI output in 36bb0f3970fa8f1423b4d1b0868ba25db0c79901.

**Comment by jonrkarr** [comment]
Fixed in dac3ea3c102d415984e8b53144a6c2bf8f0df175.

A `wc_lang` build should have been triggered from `obj_model` build 398. A build was incorrectly not triggered because a previous build of `wc_lang` had been canceled, and the triggering machinery wasn't correctly handling canceled (not run, and infrastructure fail) builds.
