### ISSUE TITLE
build dependencies when 'git revert' is pushed

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/karr_lab_build_utils#24]
Jonathan, dependencies were not built when I pushed a 'git revert'. See this build of obj_model: https://circleci.com/gh/KarrLab/obj_model/445. Rebuilding didn't trigger dependency builds either.
However, dependencies should be built when a revert is pushed because the repo being pushed may be in a state that's not been previously tested downstream. The example above illustrates this:

- the push for build 443 contained multiple commits, and its build failed
- the push for build 444 reverted one of the commits in the push for build 443, and it succeeded
- failing to test the dependencies of the push for build 444 failed to test the downstream consequences of the other commits in the push for build 443

**Comment by jonrkarr** [comment]
I don't understand the issue. Can you clarify?

443 didn't trigger downstream builds because it failed. I thought its unnecessary to build downstream dependencies after failures because the failure already tells you that the downstream dependencies may be broken. It seemed like this would just create more email notifications due to the same failure.

All five downstream builds were triggered from 444 and 445:
- datanator
- wc_kb
- wc_lang: this triggered wc_lang builds 560 and 561
- wc_rules
- wc_sim

What build(s) were you expecting?

**Comment by jonrkarr** [comment]
I'm closing this issue because there doesn't appear to be a problem.
