### ISSUE TITLE
Documentation of --test-path

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/karr_lab_build_utils#35]
It's not how to format an argument for `--test-path`.  A pathname relative to the root of the package, like `tests/test_foo.py` doesn't work. E.g., this attempt in `wc_sim` failed:

    karr_lab_build_utils3 run-tests --with-xunit --with-coverage --verbose --test-path tests/examples/test_minimal_simulation.py

    ...
    __________ ERROR collecting tests/examples/test_minimal_simulation.py __________
    ImportError while importing test module '/root/project/tests/examples/test_minimal_simulation.py'.
    Hint: make sure your test modules/packages have valid Python names.
    Traceback:
    tests/examples/test_minimal_simulation.py:12: in <module>
        from examples.minimal_simulation import RunMinimalSimulation
    E   ModuleNotFoundError: No module named 'examples.minimal_simulation'

**Comment by jonrkarr** [comment]
I believe this is a pytest issue

**Comment by jonrkarr** [comment]
The value of the argument should be a path, either relative to the current directory or an absolute path.

In CircleCI, this command is run from the root of the package. In that case, `tests/examples/test_minimal_simulation.py` is a valid argument.

It looks like pytest is correctly finding the test, but that `/package_root/examples/minimal_simulation.py` doesn't exist or isn't in a module (i.e. no `__init__.py`). 

Without knowing more context, this sounds like an issue with the packaging of `wc_sim` (not including the `examples` directory in the wheel package). Specifically, this may be because the examples aren't included in the `package_data` in `setup.py`. 

One way around this, is to install `wc_sim` with the `-e` option. Then you can test `de_sim` with all of the examples and fixtures from `wc_sim`. (You could also identify these files in `wc_sim/setup.py`. However, they probably shouldn't be identified in `setup.py` because they don't need to be distributed with `wc_sim` via PyPI.)

`MANIFEST.in` and `setup.py` only need to identify the files needed to run the package. They do not need to identify additional files needed to test or document the package.
